# Generated by Django 5.1.1 on 2024-10-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
